### ISSUE TITLE
Can not add add Identity with version 2.3.3

### ISSUE THREAD

**Issue by yangjian102621** [MichaelFedora/unofficial-blockstack-extension#14]
well, i meet an exception when add a new identity .

![image](https://user-images.githubusercontent.com/4746061/62405341-c684e780-b5ce-11e9-80b2-f7554f7d5795.png)
 
and the pop window is blocked.

![image](https://user-images.githubusercontent.com/4746061/62405347-db617b00-b5ce-11e9-82a8-a26e5a88f88f.png)

**Comment by MichaelFedora** [comment]
Hey, is this on Chrome or Firefox? The cross-window communication thing can be a little buggy.

**Comment by yangjian102621** [comment]
@MichaelFedora 

Thanks for reply this issue. i got the problem in chrome.

![image](https://user-images.githubusercontent.com/4746061/62435779-07683200-b770-11e9-8bd9-74c55e4e3483.png)

But it can not be added in pop window, must be open in a new full window.

![image](https://user-images.githubusercontent.com/4746061/62435869-3ed6de80-b770-11e9-952f-392fb9ded831.png)

**Comment by MichaelFedora** [comment]
I was able to duplicate the error and am now looking into it, thanks for you report!

**Comment by yangjian102621** [comment]
@MichaelFedora My pleasure, if you fix the bug, just `@` me to close the issue.

Thanks.

**Comment by MichaelFedora** [comment]
@yangjian102621 this will be fixed in the next version.

Thank you again for your help!
